trigger:
  - none

parameters:
  - name: serviceConnectionName
    type: string

  - name: resourceGroupName
    type: string

  - name: location
    type: string

  - name: logicAppName
    type: string

  - name: storageAccountName
    type: string

  - name: roleDefinitionID
    type: string

steps:
  - script: |
      echo "serviceConnectionName: ${{ parameters.serviceConnectionName }}"
      echo "resourceGroupName: ${{ parameters.resourceGroupName }}"
      echo "location: ${{ parameters.location }}"
      echo "logicAppName: ${{ parameters.logicAppName }}"
      echo "storageAccountName: ${{ parameters.storageAccountName }}"
      echo "roleDefinitionID: ${{ parameters.roleDefinitionID }}"
    displayName: "Debug: Print pipeline parameters"

  - task: AzureCLI@2
    displayName: "Validate Logic App ARM template"
    inputs:
      connectedServiceNameARM: "${{ parameters.serviceConnectionName }}"
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
        az deployment group validate \
          --name "LogicAppDeployment" \
          --resource-group "${{ parameters.resourceGroupName }}" \
          --template-file "$(System.DefaultWorkingDirectory)/logicapp.template.json" \
          --parameters "$(System.DefaultWorkingDirectory)/logicapp.parameters.json" \

  - task: AzureResourceGroupDeployment@2
    displayName: "Deploy Logic App ARM Template"
    inputs:
      ConnectedServiceName: "${{ parameters.serviceConnectionName }}"
      action: "Create Or Update Resource Group"
      resourceGroupName: "${{ parameters.resourceGroupName }}"
      location: "${{ parameters.location }}"
      csmFile: "$(System.DefaultWorkingDirectory)/logicapp.template.json"
      csmParametersFile: "$(System.DefaultWorkingDirectory)/logicapp.parameters.json"
      overrideParameters: >
        -location "${{ parameters.location }}"
        -logicAppName "${{ parameters.logicAppName }}"
        -storageAccountName "${{ parameters.storageAccountName }}"
      deploymentName: "LogicAppDeployment"
      deploymentMode: "Incremental"
      deploymentOutputs: "LogicAppArmOutputs"

  - task: PowerShell@2
    name: "SetDeploymentOutputVariables"
    displayName: "Set Deployment Output Variables"
    inputs:
      targetType: inline
      script: |
        $armOutputObj = '$(LogicAppArmOutputs)' | ConvertFrom-Json
        $armOutputObj.PSObject.Properties | ForEach-Object {
          $keyname = $_.Name
          $value = $_.Value.value

          # Creates a standard pipeline variable
          Write-Output "##vso[task.setvariable variable=$keyName;issecret=false]$value"

          # Display keys in pipeline
          Write-Output "output variable: $keyName"
        }
      pwsh: true

  - task: AzureResourceGroupDeployment@2
    displayName: "Deploy RBAC ARM Template"
    inputs:
      ConnectedServiceName: "${{ parameters.serviceConnectionName }}"
      action: "Create Or Update Resource Group"
      resourceGroupName: "${{ parameters.resourceGroupName }}"
      location: "${{ parameters.location }}"
      csmFile: "$(System.DefaultWorkingDirectory)/rbac.template.json"
      csmParametersFile: "$(System.DefaultWorkingDirectory)/rbac.parameters.json"
      overrideParameters: >
        -roleDefinitionID "${{ parameters.roleDefinitionID }}"
        -principalId "$(logicAppManagedIdentityPrincipalId)"
      deploymentName: "RBACDeployment"
      deploymentMode: "Incremental"
